version: '3.9'
services:
  app:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/app
    depends_on:
      - db 
      - redis

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6378:6379
